moedas = {
    "USD": "Dólar dos EUA",
    "EUR": "Euro",
    "GBP": "Libra Esterlina",
    "CAD": "Dólar Canadense",
    "AUD": "Dólar Australiano",
    "JPY": "Iene Japonês",
    "RUB": "Rublo Russo",
    "BRL": "Real Brasileiro",
    "ARS": "Peso Argentino",
    "CLP": "Peso Chileno",
    "BOB": "Bolíviano da Bolívia",
    "IDR": "Rupia Indonésia",
    "CZK": "Coroa Checa",
    }